---
name: CI

######################################################################
## minute         0-59
## hour           0-23
## day of month   1-31
## month          1-12
## day of week    0-7
######################################################################

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *" # 02:00 every day

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  ########################################
  # dotfiles - install & uninstall
  ########################################
  uninstall-install-uninstall:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    env:
      CI: 1
      NONINTERACTIVE: 1
      # Uncomment to help debug Homebrew issues
      # HOMEBREW_VERBOSE: 1
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Bootstrap - Uninstall
      - name: Bootstrap - Uninstall
        shell: bash
        run: ./bootstrap.sh --uninstall

      # Bootstrap - Install
      - name: Bootstrap - Install
        shell: bash
        run: ./bootstrap.sh --install

      # Bootstrap - Uninstall
      - name: Bootstrap - Uninstall
        shell: bash
        run: ./bootstrap.sh --uninstall
