name: CI

on:
  schedule:
    - cron: '0 23 * * *'
  push:
  pull_request:

# GitHub Actions Virtual Environments - https://github.com/actions/virtual-environments

jobs:
  ########################################
  # Lint
  ########################################
  shellcheck:
    runs-on: macOS-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3
      # Validate shell scripts
      - name: ShellCheck
        run: |
          brew install shellcheck -q
          shellcheck --version
          shellcheck *.sh
          shellcheck dotfiles/.bash_profile dotfiles/.bashrc
          shellcheck scripts/*.sh

  ########################################
  # SAST
  ########################################
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'                              # fetch-depth of '0' clones the entire history
      # Run SAST tool for detecting hardcoded secrets like passwords, api keys, and tokens in Git repos
      - name: Gitleaks
        uses: zricethezav/gitleaks-action@v1.6.0        # https://github.com/marketplace/actions/gitleaks

  ########################################
  # dotfiles - install & uninstall
  ########################################
  uninstall-install-uninstall:
    needs: [ shellcheck, gitleaks ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, macos-12 ]
    env:
      CI: 1
      NONINTERACTIVE: 1
      # Uncomment to help debug Homebrew issues
      # HOMEBREW_VERBOSE: 1
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Bootstrap - Uninstall
      - name: Bootstrap - Uninstall
        shell: bash
        run: ./bootstrap.sh --uninstall

      # Bootstrap - Install
      - name: Bootstrap - Install
        shell: bash
        run: ./bootstrap.sh --install

      # Bootstrap - Uninstall
      - name: Bootstrap - Uninstall
        shell: bash
        run: ./bootstrap.sh --uninstall
